MAX_INTX = 2147483647
MEMORY_RELATED = 1048575
numeric_option_dict = {
    "ArrayCopyLoadStoreMaxElem": [0, MAX_INTX],
    "ArrayOperationPartialInlineSize": [0, 64],
    "AutoBoxCacheMax": [0, MEMORY_RELATED],
    "BlockLayoutMinDiamondPercentage": [0, 100],
    "C1InlineStackLimit": [0, MAX_INTX],
    "C1MaxInlineLevel": [0, MAX_INTX],
    "C1MaxInlineSize": [0, MAX_INTX],
    "C1MaxRecursiveInlineLevel": [0, MAX_INTX],
    "C1MaxTrivialSize": [0, MAX_INTX],
    "ConditionalMoveLimit": [0, MAX_INTX],
    "DominatorSearchLimit": [0, MAX_INTX],
    "EliminateAllocationArraySizeLimit": [0, MAX_INTX],
    "EliminateAllocationFieldsLimit": [0, MAX_INTX],
    "FLOATPRESSURE": [0, MAX_INTX],
    "FreqCountInvocations": [1, MAX_INTX],
    "FreqInlineSize": [0, MAX_INTX],
    "INTPRESSURE": [0, MAX_INTX],
    "ImplicitNullCheckThreshold": [0, MAX_INTX],
    "InlineSmallCode": [0, MAX_INTX],
    # "InstructionCountCutoff": [0, MAX_INTX],
    "LiveNodeCountInliningCutoff": [0, 536870911],
    "LoopMaxUnroll": [0, MAX_INTX],
    "LoopOptsCount": [5, 43],
    "LoopPercentProfileLimit": [10, 100],
    "LoopStripMiningIterShortLoop": [0, MAX_INTX],
    "LoopStripMiningIter": [0, MAX_INTX],
    # "LoopUnrollLimit": [0, 536870911],
    "LoopUnrollMin": [0, MAX_INTX],
    "MaxNodeLimit": [1000, MAX_INTX // 3],
    # "MaxInlineLevel": [0, MAX_INTX],
    # "MaxInlineSize": [0, MAX_INTX],
    # "MaxJumpTableSize": [0, MAX_INTX],
    # "MaxLabelRootDepth": [100, MAX_INTX],
    # "MaxLoopPad": [0, MAX_INTX],
    # "MaxRecursiveInlineLevel": [0, MAX_INTX],
    # "MaxTrivialSize": [0, MAX_INTX],
    # "MaxVectorSize": [4, 1073741824],
    # "MinJumpTableSize": [0, MAX_INTX],
    "MultiArrayExpandLimit": [0, MAX_INTX],
    "NestedInliningSizeRatio": [0, 100],
    "NodeCountInliningCutoff": [0, MAX_INTX],
    'NodeCountInliningStep': [0, MAX_INTX],
    "NumberOfLoopInstrToAlign": [0, MAX_INTX],
    "OptoPrologueNops": [0, 128],
    "PartialPeelNewPhiDelta": [0, MAX_INTX],
    "RegisterCostAreaRatio": [0, MAX_INTX],
    "StressLongCountedLoop": [0, MAX_INTX],
    "StressSeed": [0, MAX_INTX],
    "TrackedInitializationLimit": [0, 65535],
    "TypeProfileMajorReceiverPercent": [0, 100],
    "UnrollLimitForProfileCheck": [0, MAX_INTX],
    "ValueMapMaxLoopSize": [0, 128],
    "ValueSearchLimit": [0, MAX_INTX]
}
