// Generated by Java* Fuzzer test generator (1.0.001). Mon Aug 29 10:22:46 2022
public class Test {

    public static final int N = 400;

    public static volatile long instanceCount=-27028L;
    public static byte byFld=-125;
    public static double dArrFld[]=new double[N];

    static {
        FuzzerUtils.init(Test.dArrFld, -1.28953);
    }

    public static long vMeth_check_sum = 0;
    public static long sMeth_check_sum = 0;
    public static long vMeth1_check_sum = 0;

    public static void vMeth1(float f, int i) {

        int i1=-52251, i2=13264, i3=52757, i4=16731, i5=26234, i6=-225, iArr[]=new int[N];
        boolean b=true;

        FuzzerUtils.init(iArr, -235);

        i = i;
        for (i1 = 1; i1 < 210; i1++) {
            switch (((-50895 >>> 1) % 1) + 49) {
            case 49:
                Test.byFld <<= (byte)4;
            }
            for (i3 = 1; i3 < 8; i3++) {
                for (i5 = 1; i5 < 2; ++i5) {
                    i6 = (int)6L;
                    f += i5;
                    iArr[i5 + 1] >>= i;
                    i6 = i6;
                    if (b) continue;
                    i |= (int)Test.instanceCount;
                    Test.dArrFld = Test.dArrFld;
                    i += i4;
                }
                iArr[i1 - 1] = (int)Test.instanceCount;
            }
        }
        vMeth1_check_sum += Float.floatToIntBits(f) + i + i1 + i2 + i3 + i4 + i5 + i6 + (b ? 1 : 0) +
            FuzzerUtils.checkSum(iArr);
    }

    public static short sMeth() {

        float f1=0.888F;
        double d=59.61423;
        int i7=212, i9=-128, i10=53322, i11=193, i12=-55847, iArr1[]=new int[N];
        short s1=-22020;

        FuzzerUtils.init(iArr1, 1);

        vMeth1(f1, -64);
        d = 1;
        while (++d < 182) {
            i7 = (int)Test.instanceCount;
        }
        Test.instanceCount |= s1;
        for (int i8 : iArr1) {
            for (i9 = 1; i9 < 4; ++i9) {
                i10 += (int)f1;
                i7 += i7;
                for (i11 = i9; i11 < 2; ++i11) {
                    boolean b1=false;
                    f1 += (((i11 * i10) + i7) - Test.instanceCount);
                    if (b1) break;
                    i7 = i12;
                    i7 *= 15218;
                    i12 = i8;
                    i8 += i12;
                }
            }
        }
        long meth_res = Float.floatToIntBits(f1) + Double.doubleToLongBits(d) + i7 + s1 + i9 + i10 + i11 + i12 +
            FuzzerUtils.checkSum(iArr1);
        sMeth_check_sum += meth_res;
        return (short)meth_res;
    }

    public static void vMeth(short s) {


        Test.instanceCount >>= sMeth();
        vMeth_check_sum += s;
    }

    public void mainTest(String[] strArr1) {

        int i13=316, i14=-139, i15=145, i16=5, i17=-11403, i18=23106, i19=-231, i20=67;
        float f2=7.229F, f3=-45.601F;
        boolean b2=true;
        double d1=1.98379;
        short sArr[][]=new short[N][N];

        FuzzerUtils.init(sArr, (short)19026);

        vMeth((short)(-1528));
        Test.instanceCount *= Test.instanceCount;
        Test.instanceCount *= i13;
        for (f2 = 18; f2 < 312; f2++) {
            if (true) {
                i15 = 1;
                do {
                    f3 -= i14;
                } while (++i15 < 86);
            }
            i13 *= i15;
            i16 = 1;
            do {
                i14 += i16;
                for (i17 = 1; i17 < 1; ++i17) {
                    if (b2) continue;
                    i13 += (i17 | i14);
                }
                Test.instanceCount *= i13;
                for (i19 = 1; 1 > i19; i19++) {
                    d1 = i18;
                }
                i13 = i19;
                if (b2) {
                    sArr[(int)(f2 + 1)][(int)(f2 - 1)] <<= (short)i18;
                } else {
                    f3 = i17;
                    if (b2) {
                        f3 *= i17;
                    } else {
                        if (true) continue;
                        i18 += (((i16 * f2) + i14) - i13);
                    }
                    Test.byFld += (byte)d1;
                    i18 += i16;
                }
                i13 = i14;
                Test.byFld ^= (byte)i20;
            } while (++i16 < 86);
        }
        i20 >>= i14;
        i13 += i18;

        FuzzerUtils.out.println("i13 f2 i14 = " + i13 + "," + Float.floatToIntBits(f2) + "," + i14);
        FuzzerUtils.out.println("i15 f3 i16 = " + i15 + "," + Float.floatToIntBits(f3) + "," + i16);
        FuzzerUtils.out.println("i17 i18 b2 = " + i17 + "," + i18 + "," + (b2 ? 1 : 0));
        FuzzerUtils.out.println("i19 i20 d1 = " + i19 + "," + i20 + "," + Double.doubleToLongBits(d1));
        FuzzerUtils.out.println("sArr = " + FuzzerUtils.checkSum(sArr));

        FuzzerUtils.out.println("Test.instanceCount Test.byFld Test.dArrFld = " + Test.instanceCount + "," + Test.byFld
            + "," + Double.doubleToLongBits(FuzzerUtils.checkSum(Test.dArrFld)));

        FuzzerUtils.out.println("vMeth1_check_sum: " + vMeth1_check_sum);
        FuzzerUtils.out.println("sMeth_check_sum: " + sMeth_check_sum);
        FuzzerUtils.out.println("vMeth_check_sum: " + vMeth_check_sum);
    }
    public static void main(String[] strArr) {

        try {
            Test _instance = new Test();
            for (int i = 0; i < 10; i++ ) {
                _instance.mainTest(strArr);
            }
         } catch (Exception ex) {
            FuzzerUtils.out.println(ex.getClass().getCanonicalName());
         }
    }
}
///////////////////////////////////////////////////////////////////////
//DEBUG  Test ->  Test
//DEBUG  main ->  main
//DEBUG  mainTest ->  mainTest
//DEBUG  vMeth ->  vMeth mainTest
//DEBUG  sMeth ->  sMeth vMeth mainTest
//DEBUG  vMeth1 ->  vMeth1 sMeth vMeth mainTest
//DEBUG  Depth = 3
//DEBUG  Classes = 1
//DEBUG  static objects = {}
