import Mutation.SeedPool;
import Mutation.MutationEntry;
import Preprocess.Config;
import Preprocess.Prepare;
import org.apache.commons.cli.*;

/**
 * @program: Juzz
 * @description:
 * @author: Haoxiang Jia
 * @create: 2022-07-14 15:30
 **/
public class MainEntry {
    public static void main(String[] args) throws Exception {
        Options options = new Options();
        options.addOption("jdkPath", true, "the tested jdk path");
        options.addOption("seedPath", true, "the seed path");
        options.addOption("testNumber", true, "the test number generated by JavaFuzzer");
        options.addOption("mutationRound", true, "the mutation round");
        CommandLineParser parser = new DefaultParser();
        CommandLine cmd = parser.parse(options, args);
        Config config = new Config(cmd.getOptionValue("jdkPath"), cmd.getOptionValue("seedPath"));
        Prepare prepare = new Prepare(config);
        prepare.preprocess();//preprocess the seeds and construct the prior knowledge from the regression test
//        SeedPool seedPool = new SeedPool(cmd.getOptionValue("testNumber")); //generate the seed pool
//        MutationEntry mutationEntry = new MutationEntry(config.getJdkPath(), seedPool, cmd.getOptionValue("mutationTime"));

    }
}